export const GET_ARTICLE_LIST = "GET_ARTICLE_LIST";
export const GET_SINGLE_ARTICLE = "GET_SINGLE_ARTICLE";
export const BACK_TO_ARTICLE_LIST = "BACK_TO_ARTICLE_LIST";
export const CATEGORY_SELECTION = "CATEGORY_SELECTION";